version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "22"
  commands:
    # Install pnpm
    - npm install -g pnpm@latest
    # Install dependencies
    - cd docs && pnpm install --frozen-lockfile
    # Build Docusaurus site
    - cd docs && pnpm run build
    # Move built files to _readthedocs/html for RTD
    - mkdir -p _readthedocs/html
    - cp -r docs/build/* _readthedocs/html/
