name: Release Binaries

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build-deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch: x86_64
          - target: aarch64-unknown-linux-gnu
            arch: aarch64
    steps:
      - uses: actions/checkout@v4

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Build .deb package
        run: |
          cargo deb --target ${{ matrix.target }}
          DEB_FILE=$(find target/${{ matrix.target }}/debian -name "*.deb")
          VERSION=${GITHUB_REF#refs/tags/}
          cp "$DEB_FILE" "wasmrun-${VERSION}-${{ matrix.arch }}.deb"

      - name: Upload .deb artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: "wasmrun-*.deb"
          draft: ${{ contains(github.ref_name, '-') }}
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
